### ISSUE TITLE
Should be able to query Hummedia's catalog

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#141]

**Comment by trevren11** [comment]
Should the items on hummedia be added to the list when using the check in page? Is that what this is saying or a separate page where they are listed?

**Comment by webnard** [comment]
I believe it's meant to show up on the check out page, so an attendant can
say something like, "Oh, we don't have a physical copy here, but we can set
you up with something on Hummedia for your class."

On Thu, Jan 21, 2016 at 3:17 PM, trevren11 <notifications@github.com> wrote:

> Should the items on hummedia be added to the list when using the check in
> page? Is that what this is saying or a separate page where they are listed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hlrdesk/issues/141#issuecomment-173695757>.
>



-- 
 ian hunter

**Comment by trevren11** [comment]
I imagine this needs the hummedia patch @dcravenus  is working on correct?

**Comment by stevethomas19** [comment]
@webnard Do we need to use the **byu-hummedia-api** to query Hummedia?

**Comment by stevethomas19** [comment]
This issue will be re-discussed as we work on the next version of hummedia. This issue will be closed for now.
