### ISSUE TITLE
Admin should be able to view information about a patron

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#20]

**Comment by trevren11** [comment]
What kind of information do we want to list?

**Comment by trevren11** [comment]
Basic info will be there, but do we also want checkout history, fines paid, fines owed etc?

**Comment by trevren11** [comment]
Get information that requires FERPA. Email and phone. Also checkout history. Fines paid in past. (also get fines working) Harlod will get FERPA if possible

**Comment by stevethomas19** [comment]
We can't do what we wanted to do with this, when the issue was brought up. It is now null.
