### ISSUE TITLE
Redis/HLRDesk session mismatches - cookies get stale

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#212]
Sometimes the HLRDesk session may still be active, but the supplied Redis token no longer exists or is obsolete (i.e., if Redis has to be restarted for whatever reason). This allows some pages to work but kills sockets.

We need a way to either replenish the Redis data from the Koa session or prompt the user to log back in.

**Comment by stevethomas19** [comment]
This will be fixed when #328 is fixed. So I'm going to close it.
