### ISSUE TITLE
Socket message when unauthorized

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#225]
When a user doesn't have permission to do something, their socket should receive a message prompting them to log in (if unauthenticated) or receive elevated permissions (if not an admin and necessary)

**Comment by stevethomas19** [comment]
@webnard What is the status of this one. I feel like we already do this in a lot of places. Do we just need to make sure we are consistent across the app? If something still needs to be done, would you like me to look into it?

**Comment by webnard** [comment]
You were working on a pull request to automatically redirect the user to the CAS login box, right, if they weren't logged in when a socket request happened? That's what this is referencing. If that's complete, or this is a dupe, you can close this issue.
