### ISSUE TITLE
Custom Logger

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#255]
I don't want console.error statements showing up when I'm running automated tests and I do something on purpose to cause an error. It'd be nice to have a custom logger that we can use to disable when running automated tests, and perhaps to also provide a timestamp.

**Comment by Luke1298** [comment]
I like that idea.
Maybe in just a utils file? For costume server usages?

**Comment by Luke1298** [comment]
*utils folder

**Comment by webnard** [comment]
Sure--you wanna handle this one?

**Comment by stevethomas19** [comment]
PR - #376 makes it so console.error statements do not appear on the console. Instead they are written to a debug.log file with a timestamp included each time a test is run.
