### ISSUE TITLE
See other Admins

### ISSUE THREAD

**Issue by Luke1298** [BYU-ODH/hlrdesk#266]
The add Admins page needs to be more interactive. What should be the default behavior if you try to make a nonexsistant an admin. Should it just reserve the "trueness" when the user first signs in? I like that Idea. Also do a "display all admins". @webnard can I get your input on this asap.

**Comment by webnard** [comment]
How about: "The NetID [NETID] does not exist in the database. Do you want to add them?"

**Comment by Luke1298** [comment]
I like it. Will get started (and hopefully finish) that tonight.

**Comment by trevren11** [comment]
Hey, the add admin doesn't work. First, if you try to add someone that does not exist, you have to add again to make them an admin. Also, if you try to delete an admin it does not do it, it updates but the value is still true, but if you delete somebody that does not exist, that adds them as an admin right away.
