### ISSUE TITLE
Error message on check-out page

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#293]
"on the check-out pg, keep getting error message. Is there specific format for inputting date/phone#? do we have to fill in all fields? -- Can't close the error box & try again - have to reselect item."

**Comment by webnard** [comment]
>  Can't close the error box & try again - have to reselect item.

This is not actually the case, but because of #298, it may appear to not be able to be closed.

**Comment by alexcdahl** [comment]
I think it's because the "close" button doesn't do anything. I'll give it functionality, but do we need a close button since the modal window already has the x in the upper right?

**Comment by webnard** [comment]
Nope! Wanna trash it?

**Comment by webnard** [comment]
See #313
