### ISSUE TITLE
Deleting languages

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#295]
"After deleting languages you can't search for any language/have to click on the 'Edit Language' tab to be able to search for languages again."

**Comment by webnard** [comment]
@alexcdahl -- Have this and #294 been fixed?

**Comment by alexcdahl** [comment]
No, not yet. I'll get to work on it now. It'll be done soon. #294 is assigned to Derrick, but I can do it if you'd like.

**Comment by webnard** [comment]
Oh, you're right. If I remember correctly, Derrick had already started on
that, so we'll go ahead and let him finish.

On Mon, Jun 15, 2015 at 4:22 PM, Alexander Dahl <notifications@github.com>
wrote:

> No, not yet. I'll get to work on it now. It'll be done soon. #294
> <https://github.com/BYU-ODH/hlrdesk/issues/294> is assigned to Derrick,
> but I can do it if you'd like.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hlrdesk/issues/295#issuecomment-112227514>.
>



-- 
 ian hunter

**Comment by stevethomas19** [comment]
PR #375 fixes this issue.
