### ISSUE TITLE
Language adding

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#296]
"When added a language it creates the language four times, but once you refresh the page and search the language you created it is in there only once."

**Comment by alexcdahl** [comment]
I'm not able to recreate this error.

**Comment by webnard** [comment]
@alexcdahl Have you tested in Firefox?

**Comment by alexcdahl** [comment]
Yeah, but I just get an entirely different error. It freezes up and doesn't add the language.

**Comment by webnard** [comment]
nuts. Okay. Do you want to close this issue and open a new one?

On Thu, Jun 11, 2015 at 4:58 PM, Alexander Dahl <notifications@github.com>
wrote:

> Yeah, but I just get an entirely different error. It freezes up and
> doesn't add the language.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hlrdesk/issues/296#issuecomment-111300251>.
>



-- 
 ian hunter

**Comment by alexcdahl** [comment]
Sure thing.
