### ISSUE TITLE
Automated Email - Displays table of automated reminder emails for checked-out items

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#30]

**Comment by Luke1298** [comment]
For clarity:

We want it to send a email remind say the day before it's due?

**Comment by webnard** [comment]
Not sure. When would be appropriate, @dylhoff? It might be contingent on how long people usually check things out for.

Additionally, I'm not sure we'd even want an interface for this. It should probably all be done with a cron job.
