### ISSUE TITLE
Check-in page needs to show phone number, full name, and email address

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#301]

**Comment by webnard** [comment]
See https://web.byu.edu/wiki/ldap-authentication and https://www.npmjs.com/package/ldap

**Comment by webnard** [comment]
@alexcdahl I'm going to work on a method for retrieving a user's details from the LDAP server, so don't worry about that for now. Have you started on the implementation of displaying extra information yet? If not, I might just take this task and finish it up for our push live today.

**Comment by alexcdahl** [comment]
It's all yours.
