### ISSUE TITLE
Can't Edit Item Call Number

### ISSUE THREAD

**Issue by alexcdahl** [BYU-ODH/hlrdesk#330]

**Comment by trevren11** [comment]
Should we add a hash for the item that will never change so when we change the call number the rest of the information will not move elsewhere? (Currently I know the item history is using the call number and when it changes call number has to write to the old call number saying the number has changed and on the new id that the id was changed from the previous call number)

**Comment by stevethomas19** [comment]
This is a duplicate issue that @trevren11 is working on in #332
