### ISSUE TITLE
When Adding New Item to Catalog, Can't Change the Date Added

### ISSUE THREAD

**Issue by alexcdahl** [BYU-ODH/hlrdesk#331]

**Comment by trevren11** [comment]
How important is this/is it used/needed?

**Comment by stevethomas19** [comment]
@alexcdahl @trevren11 What if for each of the disabled fields (date added, date edited, last edited by) we make them hidden. That way people who add or edit items won't try to edit those fields. We don't want them edited anyway.

**Comment by trevren11** [comment]
We want them there to see who changed the item and when it was added, but they probably shouldn't be inside input fields, just regular text so they wouldn't even have the option to change. But I don't think we need the option to change the date added to we?

**Comment by stevethomas19** [comment]
I agree with you. No change, and if they are plain text they won't appear editable.

**Comment by stevethomas19** [comment]
PR #374 resolves this based on discussion above.
