### ISSUE TITLE
Can't do same-day returns

### ISSUE THREAD

**Issue by alexcdahl** [BYU-ODH/hlrdesk#343]
Sometimes items are checked out and meant to be returned later that same day. However, this can't be done and gives an error. It would be preferable to make same-day returns due at closing time that day.

**Comment by webnard** [comment]
Is the issue that items can't be returned the same day, or that items can't
be marked as due the same day?

On Mon, Jan 25, 2016 at 12:29 PM, Alexander Dahl <notifications@github.com>
wrote:

> Sometimes items are checked out and meant to be returned later that same
> day. However, this can't be done and gives an error. It would be preferable
> to make same-day returns due at closing time that day.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hlrdesk/issues/343>.
>



-- 
 ian hunter

**Comment by alexcdahl** [comment]
They can't be marked as due the same day.
