### ISSUE TITLE
Repeated check in/out causes error

### ISSUE THREAD

**Issue by alexcdahl** [BYU-ODH/hlrdesk#347]
If the same item is checked out and checked back in in a short period of time, it cannot be checked out without throwing an error.

**Comment by alexcdahl** [comment]
After extensive tinkering with this, I still haven't been able to pinpoint what the issue is, but I have noticed that more calls to the database seem to reduce the frequency of this happening. For example, I had a few console.logs surrounding the queries in the js file and it was much more difficult to recreate the error. This makes me wonder if it's something going on while connecting to the database.

**Comment by trevren11** [comment]
More calls throw the error less frequently? That seems odd.

**Comment by stevethomas19** [comment]
@alexcdahl Is this still an issue? I tried duplicating it and was not able to.

**Comment by alexcdahl** [comment]
Kinda... this is a duplicate.
