### ISSUE TITLE
Migrations doesn't clear terminal color.

### ISSUE THREAD

**Issue by webnard** [BYU-ODH/hlrdesk#364]
![terminal](https://cloud.githubusercontent.com/assets/1213808/14573962/9dbf8dd6-0326-11e6-8d54-b5d1945a75f2.png)

**Comment by trevren11** [comment]
NOOOOO!!!! Does the server not recognize the colors? The last line prints out what should be the color, and also the beginning has a \n as well, that doesn't happen to my machine. We could remove the colors or just add a setaf? It seems to work with the setaf but not the colors used in the echo commands.

**Comment by webnard** [comment]
You need to use `echo -e`in order for the `\` sequences to work. I think that should fix everything.
