### ISSUE TITLE
Be able to add employee

### ISSUE THREAD

**Issue by stevethomas19** [BYU-ODH/hlrdesk#378]
talked with harold. We need a button and form that will allow us to add an employee without having to go straight to the DB.

**Comment by webnard** [comment]
Does the /employees endpoint still provide access to the mkadmin function?
Luke had set it up:
https://github.com/BYU-ODH/hlrdesk/blob/cde7d36127d62053cf2ec8f907e9fd27c3067733/core/app.js#L300

On Mon, Apr 25, 2016 at 5:32 PM, Stephen Thomas <notifications@github.com>
wrote:

> talked with harold. We need a button and form that will allow us to add an
> employee without having to go straight to the DB.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BYU-ODH/hlrdesk/issues/378>
>



-- 
 ian hunter

**Comment by stevethomas19** [comment]
Yep! Sorry my bad. False alarm everyone. I'm closing this issue.
